- hosts: terraform-ansible
  tasks:
  - name: Installing python3 and virtualenv
    apt:
      pkg: 
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: Installing dependencies with PIP (Django and Django REST)
    pip: 
      virtualenv: /home/ubuntu/tcc/venv
      name:
        - django
        - djangorestframework
  - name: Checking if the project already exists 
    stat:
      path: /home/ubuntu/tcc/setup/settings.py
    register: project
  - name: Starting the project
    shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
    when: not project.stat.exists
  - name: Changing hosts from settings
    lineinfile:
      path: /home/ubuntu/tcc/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
